# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 840b51aaa8d2799d1a3353f08e3b7687eed5b007f3e4935e8246cfae061eada4db2edfb5f0f3b0348ed046f5546d5426bdb8c7c55c5166aea1a6287d5690d0c6

test:
  secret_key_base: 30c22b5ddf58b064640f2225d74ea59e923086d7c26a25e9ad7f5370c79e1425a02f76fc742013d0cb54d4e09fbce5fa3ac5c14cf5239a9368f151f58b73e397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
